import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// import { Source_Code_Pro } from 'next/font/google'

// const sourceCodePro = Source_Code_Pro({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-source-code-pro', // optional for Tailwind usage
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${sourceCodePro.variable} antialiased`}
      >
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: "black",
              border: "1px solid white",
              color: "#00ff88",
              fontFamily: "monospace",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
